sudo: required
language: node_js
dist: trusty

node_js:
  - "8"

services:
  docker

script:
  - docker build .
deploy:
  provider: npm
  email: rzr@users.sf.net
  api_key:
    secure: GQTf9EMvXSmsY0nlKasisXXLkrEtozZXjFqweMXnjTJVKCrW/DZItz4sePOiMLHp0HKAxd3fx1yxUTBUDgbekf8ikwCvy7pvNiJEzAd0agrVPnAv4N6E7B01jX271YAZK9aTdPhdrvSc+B8lqxFLjghye4kOE27d8/6AKvprvPRdK7AeZg56rB9JO1ifTdL4Xwy7MCPryTAoo+Le6df1o2ApsC+QKhawz203TX4DuG3CdbrfIeg2FvHtIKPW+QfugjWaYyi3d09L/RYvlNgUD3y/AQ3zrzHGrqcVt1PR6PTfNjaI2QK2lHTAoAJfmIa8mJCi71A+SxjVBZlaE/neDC91a0P1wOb1hb5R1dJa9P1aALBOZbzrdgKu3QdbCF1efWb+ecDeu6CmK7Q7EXpINPi7X0zUUv6wnLW1w//6PaU9JBEex1Cn5PRgAjfFPCgLTr0O6E33vDA9s3pZLDHliyE4VEaEk/r3Q7myTuf4JWWX4kTVIBL6Zo95aQ9xDvUfcq8Y48slY2OYMjrRKQwfghqztHp1FLGI6EqOqrXN2vwazvlIBqZcvsL8GV57Em8i3JHNIq9sTdldRwrQ2Lmf/TjYgR5SyYdIpyGm7Lw4QwLonLTNUmOP2o+qiUadKkuV6RSxOWtf69bGuE5LV9ib/6UTlXzUwor6dENSdzIJPls=
  on:
    tags: true
    repo: rzr/generic-sensors-lite
